-- 0004 — "Delete my account" from account.html.
-- request_account_deletion(): called by the signed-in user (RPC). Records what
-- the owner must clean up by hand (CV file, candidate rows), emails the owner
-- through Resend (pg_net), then deletes the login. profiles cascades away;
-- candidates.account_id is set NULL (schema.sql) so the pipeline data stays
-- until the owner removes it.
--
-- Needs a Vault secret named resend_api_key (set once, outside this file):
--   select vault.create_secret('<key>', 'resend_api_key');

create extension if not exists pg_net with schema extensions;

create table if not exists deletion_requests (
  id              bigint generated by default as identity primary key,
  user_id         uuid not null,
  email           text,
  candidate_slug  text,
  cv_url          text,
  requested_at    timestamptz not null default now(),
  handled_at      timestamptz,
  notes           text
);
alter table deletion_requests enable row level security;   -- no policies: owner only

create or replace function request_account_deletion()
returns void
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  uid   uuid := auth.uid();
  mail  text;
  slug  text;
  cv    text;
  key   text;
begin
  if uid is null then
    raise exception 'not signed in';
  end if;

  select email into mail from auth.users where id = uid;
  select c.slug, c.cv_url into slug, cv from candidates c where c.account_id = uid;

  insert into deletion_requests (user_id, email, candidate_slug, cv_url)
  values (uid, mail, slug, cv);

  select decrypted_secret into key from vault.decrypted_secrets where name = 'resend_api_key';
  if key is not null then
    perform net.http_post(
      url     := 'https://api.resend.com/emails',
      headers := jsonb_build_object('Authorization', 'Bearer ' || key, 'Content-Type', 'application/json'),
      body    := jsonb_build_object(
        'from',    'Phantasma <auth@solvephantasma.com>',
        'to',      jsonb_build_array('consult@solvephantasma.com'),
        'subject', 'Account deletion: ' || coalesce(mail, uid::text),
        'text',    'A client deleted their account on solvephantasma.com.' || E'\n\n' ||
                   'Email:      ' || coalesce(mail, '—')  || E'\n' ||
                   'Candidate:  ' || coalesce(slug, '— (no candidate row linked)') || E'\n' ||
                   'CV file:    ' || coalesce(cv, '—')    || E'\n' ||
                   'Requested:  ' || to_char(now(), 'YYYY-MM-DD HH24:MI') || ' UTC' || E'\n\n' ||
                   'To do by hand within 7 days: delete the CV from Storage (bucket cvs), ' ||
                   'remove or anonymise the candidates / shortlists / sends rows, then mark ' ||
                   'deletion_requests.handled_at.'
      )
    );
  end if;

  delete from auth.users where id = uid;
end;
$$;

revoke all on function request_account_deletion() from public;
grant execute on function request_account_deletion() to authenticated;
